.TH CONTACTCARDS 1
.SH NAME
contactcards \- a simple address book
.SH DESCRIPTION
contactcards is a simple address book written in C.
vCards are safed  in a local database and fetched from a remote server using the cardDav protocoll.
.SH OPTIONS
.TP
.BR \-c ", " \-\-config \ \fI/path/to/a/directory/\fR
Sets the alternate configuration directory.
.TP
.BR \-d ", " \-\-debug
Runs contactcards in debugging mode.
.TP
.BR \-n "," \-\-nolocal
Runs contactcards without a local address book
.TP
.BR \-q ", " \-\-query \ \fIPATTERN\fR
Searches for \fIPATTERN\fR in the database of contactcards. Results will written to \fIstdout\fR without running the graphical frontend.
The format of the output is: e-mail <tab> full name <newline>
.TP
.BR \-v ", " \-\-verbose
Runs contactcards in verbose mode.
.TP
.BR \-V ", " \-\-version
Shows the version of contactcards.
.SH AUTHOR
Written by Florian Lehner.
