language: c

compiler:
    - gcc

before_script:
    - apt-get install libgtk-3-dev
    - apt-get install libsqlite3-dev
    - apt-get install libneon27-dev
    - apt-get install autopoint

script:
    - ./autogen.sh
    - ./configure
    - make
