language: c

compiler:
    - gcc

before_script:
    - sudo apt-get update
    - sudo apt-get install libgtk-3-dev
    - sudo apt-get install libsqlite3-dev
    - sudo apt-get install libneon27-dev
    - sudo apt-get install autopoint
    - sudo apt-get install intltool

script:
    - ./autogen.sh
    - ./configure
    - make
