language: c

sudo: required

dist: trusty

compiler:
    - gcc

cache: apt

before_install:
    - sudo apt-get clean
    # Install dependancies
    - sudo apt-get update
    - sudo apt-get install -y libgtk-3-dev
    - sudo apt-get install -y libsqlite3-dev
    - sudo apt-get install -y libneon27-dev
    - sudo apt-get install -y autopoint
    - sudo apt-get install -y intltool

install:
    - ./autogen.sh
    - ./configure
    - make
