language: c

sudo: required

dist: trusty

compiler:
    - gcc

cache: apt

before_install:
    - sudo apt-get clean
    # Trusty itself does not contain gtk3.12 which is required ...
    # so we add an external repo
    - sudo add-apt-repository -y ppa:gnome3-team/gnome3-staging
    - sudo apt-get -y update
    # Install dependancies
    - sudo apt-get install -y automake
    - sudo apt-get install -y autopoint
    - sudo apt-get install -y intltool
    - sudo apt-get install -y libneon27-dev
    - sudo apt-get install -y libsqlite3-dev
    - sudo apt-get install -y libglib2.0-dev
    - sudo apt-get install -y libgtk-3-dev

install:
    - ./autogen.sh
    - ./configure
    - make
